branches:
  only:
  - master

language: objective-c
osx_image: xcode10

script:
- xcodebuild -project BeeTee.xcodeproj -target BeeTee -sdk iphonesimulator

after_success:
- bash <(curl -s https://codecov.io/bash)
